# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Installing NPM
      run: npm install
    - name: Running unit tests
      run: npm run test:unit
    - name: Display username
      run: echo "Theo1"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

  ui_tests:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
 
    - name: Installing NPM
      run: npm install
    - name: Installing Playwright Browsers
      run: npx playwright install --with-deps
    - name: Running UI tests
      run: npm run test:ui
